---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# cebrap.lab online -  Introdução ao R

Para saber de próximos oferecimentos, entre em contato com <cebrap.lab@cebrap.org.br>


## Informações gerais

- **Ministrante:** [Beatriz Milz](https://beamilz.com/)

- **Data/horário:** 19 a 23 de agosto de 2024;  
  - Segunda, Quarta e Sexta: aula ao vivo, online, das 19h00 às 22h00. 
  - Terça e quinta: haverão tarefas para casa, para praticar os conceitos.

- **Inscrições:** <https://cursos.cebrap.org.br/>


## Materiais

### Slides

- [Slide de apresentação do curso](https://beatrizmilz.github.io/2024-08-cebrap-lab-intro-R/slides/introducao-ao-curso.html#/)

<!-- - [Slide de dicas - evitando erros](https://beatrizmilz.github.io/2023-06-cebrap-lab-intro-R/slides/aula-2.html) -->

### Scripts

Abaixo estão os scripts usados no RStudio após a aula:

Em breve!

<!-- - [R Base](https://github.com/beatrizmilz/2023-06-cebrap-lab-intro-R/blob/main/scripts-pos-aula/1-r-base.qmd) -->

<!-- - [Importação](https://github.com/beatrizmilz/2023-06-cebrap-lab-intro-R/blob/main/materiais_rstudio_cloud_pos_aula/Topico-2-importacao/2-importacao.Rmd) -->

<!-- - [Manipulação](https://github.com/beatrizmilz/2023-06-cebrap-lab-intro-R/blob/main/materiais_rstudio_cloud_pos_aula/Topico-3-manipulacao/3-manipulacao.Rmd) -->

<!-- - [Baixar zip completo](https://github.com/beatrizmilz/2023-06-cebrap-lab-intro-R/raw/main/material_completo.zip)  -->

### Exercícios

- Atenção: os arquivos dos exercícios contém as respostas.

- [Exercícios](https://github.com/beatrizmilz/2024-08-cebrap-lab-intro-R/tree/main/exercicios)


## Materiais para estudar mais

- [Livro online, gratuito e em Português: Ciência de Dados com R](https://cienciadedatos.github.io/pt-r4ds/)

- [Livro online e gratuito: Ciência de Dados em R](https://livro.curso-r.com/7-2-dplyr.html)

<!-- - [Slide Curso-R: Introdução ao R](https://curso-r.github.io/main-r4ds-1/slides/02-introducao-ao-r.html#1)  -->


<!-- - [Slide Curso-R: Importação de dados](https://curso-r.github.io/main-r4ds-1/slides/03-importacao.html#1)  -->

<!-- - [Slide Curso-R: Manipulação de dados](https://curso-r.github.io/main-r4ds-1/slides/04-manipulacao.html#1)  -->

<!-- - [Slide Curso-R: Visualizando dados com o pacote ggplot2](https://curso-r.github.io/main-r4ds-1/slides/05-ggplot2.html#1)  -->



## Outras informações

Material do curso de 2023 (ministrado por Beatriz Milz): <https://github.com/beatrizmilz/2023-06-cebrap-lab-intro-R>

Material do curso de 2022 (ministrado por Beatriz Milz): <https://github.com/beatrizmilz/cebrap-lab-intro-R-5-2022>

Material do curso de 2019 (ministrado por Leonardo Barone): <https://github.com/leobarone/cebrap_lab_programacao_r>




